export const metadata = {
    title: "کامنت  ها",
    description: "Generated by create next app",
  };

export default function ShowCommentLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return ( <>{children} </>
  );
}
