export const metadata = {
    title: "دوره ها",
    description: "Generated by create next app",
  };

export default function ShowCoursesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return ( <>{children} </>
  );
}
